# Generated by Django 4.2.3 on 2023-08-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_rename_carros_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('AB', 'Alinhamento e Balanceamento'), ('DE', 'Diagnóstico Eletrônico'), ('LAC', 'Limpeza do Sistema de Ar Condicionado'), ('LBI', 'Limpeza de Bicos Injetores'), ('LR', 'Limpeza do Radiador'), ('RAC', 'Recarga do Sistema de Ar Condicionado'), ('RSF', 'Reparo no Sistema de Freios'), ('RP', 'Revisão Preventiva'), ('TAD', 'Troca do Óleo do Diferencial'), ('TA', 'Troca de Amortecedores'), ('TB', 'Troca da Bateria'), ('TCA', 'Troca da Correia do Alternador'), ('TCD', 'Troca da Correia Dentada'), ('TFA', 'Troca do Filtro de Ar'), ('TFC', 'Troca do Filtro de Combustível'), ('TFF', 'Troca de Fluido de Freios'), ('TKE', 'Troca do Kit de Embreagem'), ('TO', 'Troca de Óleo'), ('TPF', 'Troca de Pastilhas de Freio'), ('TVI', 'Troca de Velas de Ignição')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocole', models.CharField(blank=True, max_length=32, null=True)),
                ('categoria_manutencao', models.ManyToManyField(to='servicos.categoriamanutencao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
