# Generated by Django 4.2.3 on 2023-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_categoriamanutencao_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='protocole',
        ),
        migrations.AddField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
